#
# Copyright (C) 2020-2022 Texas Instruments Incorporated - https://www.ti.com/
#	Suman Anna <s-anna@ti.com>
#
# Copyright 2023 TechNexion Ltd.
# Ray Chang <ray.chang@technexion.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= axon-am62xx.o
obj-y += ../common/tn_eeprom.o
