#
# Copyright (C) 2022 Texas Instruments Incorporated - https://www.ti.com/
# Copyright 2023 TechNexion Ltd.
# Author: Ray Chang <ray.chang@technexion.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= axon-am62ax.o
